### ISSUE TITLE
Jekyll example doesn't render `/blog` sources

### ISSUE THREAD

**Issue by bmcminn** [moonwave99/waffel#6]
Tried following the article listed regarding a blog-like rendering experience in Waffel, but it fails to generate any of my `/data/blog/...` contents into the `/public` directory. Below is the site.yml I'm using per the Jekyll example instructions on http://moonwave99.github.io/waffel/examples/cinema-blog-ala-jekyll/

``` yaml
config:
    title:                  Your Awesome Website
    google_analytics:       UA-XXXXXXX-Y
    google_webmaster_tools: xyz
    google_fonts:
        Ubuntu: 400,700,400italic
        Arvo:   400,700,400italic
structure:
    home:
        template:   home
        url:        /
    about:
        template:   about
        url:        /about
    blog:
        collection: posts
        pages:
            index:
                template:   blog/index
                url:        /blog
                priority:   0.5
                sort:
                    field: date
                    order: desc
            categories:
                template:   blog/category
                url:        /blog/category/:category
                groupBy:    category
                priority:   0.5
                sort:
                    field: date
                    order: desc
            tags:
                template:   blog/tag
                url:        /blog/tag/:tag
                groupBy:    tags
                changefreq: weekly
                priority: 0.7
                sort:
                    field: date
                    order: desc
            single:
                template:   blog/post
                url:        /blog/posts/:slug
                priority:   0.8
    404:
        template:   '404'
        url:        /404
        sitemap:    false
```
